INSERT INTO stroll (name, description, location, latitude, longitude, image) VALUES
('Central Park', 'Central Park is an 843-acre urban oasis in Manhattan, New York City, designed by landscape architects Frederick Law Olmsted and Calvert Vaux as a quintessential example of 19th-century landscape architecture and a sanctuary from city life. It features diverse elements such as meadows, woodlands, lakes, streams, winding paths, and numerous architectural and cultural landmarks like Bethesda Terrace and the Central Park Zoo.', 'Central Park, New York, NY', 40.785091, -73.968285, '_images/central_park.jpeg'),
('Eiffel Tower', 'The Eiffel Tower, a wrought-iron lattice tower, is a globally recognized symbol of Paris, France. It stands 330 meters (1,083 feet) tall, including the antenna, making it the tallest structure in Paris. Visitors can ascend by stairs or elevators to the three levels, which offer restaurants, observation decks, and panoramic views of the city.', 'Eiffel Tower, Paris, France', 48.8584, 2.2945, '_images/eiffel_tower.jpg'),
('Colosseum', 'The Colosseum is a massive, iconic, oval-shaped amphitheater in Rome, constructed from stone, concrete, and tuff, standing approximately 48 meters tall and covering about 6 acres. Built by the Flavian emperors and completed around 80 AD, this historical landmark was designed to hold 50,000 to 80,000 spectators for gladiatorial contests and public spectacles like animal hunts and battle re-enactments. Despite significant damage from earthquakes and looting, the Colosseum remains a symbol of Imperial Rome and a popular tourist attraction.', 'Colosseum, Rome, Italy', 41.8902, 12.4922, '_images/colosseum.webp'),
('Great Wall', 'The Great Wall is a vast series of fortifications in northern China, not a single continuous wall, built over 2,000 years by various dynasties to protect the empire from nomadic invaders. The most famous and well-preserved sections, built by the Ming Dynasty, stretch for thousands of miles from the coast to the desert, incorporating natural barriers like mountains and featuring walls, watchtowers, and fortresses. It is the largest man-made structure in the world and a symbol of China''s strength and engineering prowess', 'Great Wall of China, Beijing, China', 40.4319, 116.5704, '_images/great_wall.webp'),
('Louvre Museum', 'The Louvre Museum in Paris is the world''s largest and most visited art museum, housing over 35,000 artworks from antiquity to the mid-19th century across eight curatorial departments. Originally a medieval fortress and later a royal palace, it became a public museum during the French Revolution in 1793. Its collections include famous masterpieces like the Mona Lisa, the Venus de Milo, and the Winged Victory of Samothrace, all housed within the historic Louvre Palace complex and marked by I.M. Pei''s iconic glass pyramid', 'Louvre Museum, Paris, France', 48.8606, 2.3376, '_images/louvre_museum.webp'),
('Liberty', 'The Statue of Liberty is a 151-foot-tall copper statue on Liberty Island in New York Harbor, a gift from France symbolizing freedom and democracy, with the woman holding a torch and a tablet inscribed with the Declaration of Independence''s date. Designed by Frédéric Auguste Bartholdi, the statue, officially named Liberty Enlightening the World, features a crown with seven spikes, representing the continents and seas, and broken chains at her feet, signifying freedom from oppression. The copper exterior has oxidized to its iconic green color, and the statue stands on a pedestal, creating a total height of 305 feet.', 'Statue of Liberty, New York, NY', 40.6892, -74.0445, '_images/statue_of_liberty.jpg'),
('Opera House', 'An opera house is a theater specifically for opera performances, featuring a stage, orchestra pit, seating, and backstage facilities, but also serving as iconic landmarks in many cities. For example, the Sydney Opera House is a world-renowned 20th-century architectural masterpiece in Australia, known for its distinct "sails" or vaulted shells and hosting a variety of performing arts alongside opera.', 'Sydney Opera House, Sydney, Australia', -33.8568, 151.2153, '_images/opera_house.jpg'),
('Mahal', 'The Taj Mahal is a white marble mausoleum in Agra, India, featuring an octagonal structure with a prominent bulbous dome, flanked by four minarets, and situated within a large Mughal garden. Known for its architectural elegance, it combines Persian, Central Asian, and Islamic styles, with intricate floral arabesques and calligraphic inscriptions inlaid into the building''s white Makrana marble using various precious and semi-precious stones.', 'Taj Mahal, Agra, India', 27.1751, 78.0421, '_images/taj_mahal.webp'),
('Fuji', 'Mount Fuji is a towering, active stratovolcano on Japan''s Honshu island, standing as the nation''s tallest peak at 3,776 meters (12,388 feet). Known for its iconic, graceful conical shape and enduring spiritual significance, the mountain is a major cultural symbol, inspiring countless artworks and serving as a popular pilgrimage site. It last erupted in 1707, is a UNESCO World Heritage Site, and is located in the Fuji-Hakone-Izu National Park.', 'Mount Fuji, Japan', 35.3606, 138.7274, '_images/mount_fuji.jpeg'),
('Cairo', 'The Giza pyramid complex in Egypt is home to the Great Pyramid, the pyramid of Khafre, and the pyramid of Menkaure, along with their associated pyramid complexes and the Great Sphinx. All were built during the Fourth Dynasty of the Old Kingdom of ancient Egypt, between c. 2600 – c. 2500 BC.', 'Pyramids of Giza, Cairo, Egypt', 29.9792, 31.1342, '_images/giza_pyramid.jpg'),
('Familia', 'The Sagrada Família is an enormous, still-unfinished Roman Catholic basilica in Barcelona, Spain, designed by the Catalan architect Antoni Gaudí. Known for its unique blend of Art Nouveau and Catalan Modernism styles, its design is heavily inspired by nature, with a "forest-like" interior featuring tree-shaped columns and organic forms. Key features include the symbolic Latin cross layout, its 18 planned towers dedicated to religious figures, and three distinct facades depicting key events in Jesus''s life.', 'Sagrada Familia, Barcelona, Spain', 41.4036, 2.1744, '_images/sagrada_família.webp'),
('London', 'Big Ben is the name of the Great Bell within the Elizabeth Tower, a clock tower attached to the Palace of Westminster in London, which is itself a major landmark. The tower, a Gothic Revival structure over 315 feet tall with four 23-foot-wide clock faces, was completed in 1859. The 13.7-ton bell, which sounds the hour, is a symbol of British resilience, famously broadcasting its chimes on BBC radio.', 'Big Ben, London, England', 51.5007, -0.1246, '_images/big_ben.jpg'),
('Picchu', 'Machu Picchu is a 15th-century Inca citadel and UNESCO World Heritage Site in Peru''s Andes Mountains, known for its precision stonework, advanced engineering, sophisticated terraces, and astronomical alignments, all preserved in a spectacular mountain setting. Built for Emperor Pachacuti and abandoned after the Spanish conquest, it was forgotten for centuries before being brought to international attention in 1911 by historian Hiram Bingham.', 'Machu Picchu, Peru', -13.1631, -72.5450, '_images/machu_picchu.webp'),
('Wiltshire', 'Stonehenge is a prehistoric monument on the Salisbury Plain in Wiltshire, England, famous for its iconic ring of large standing stones, including massive sarsens and smaller bluestones, built in several stages over 5,000 years ago.', 'Stonehenge, Wiltshire, England', 51.1789, -1.8262, '_images/stonehenge.jpg'),
('Redeemer', 'Christ the Redeemer is a colossal Art Deco statue of Jesus Christ in Rio de Janeiro, Brazil, located atop Corcovado mountain, symbolizing peace with its open arms. Completed in 1931, the 30-meter (98 ft) tall statue of reinforced concrete is covered in soapstone tiles and sits on an 8-meter (26 ft) pedestal, spanning 28 meters (92 ft) wide. It is an iconic landmark for both Rio and Brazil and was voted one of the New Seven Wonders of the World.', 'Christ the Redeemer, Rio de Janeiro, Brazil', -22.9519, -43.2105, '_images/redeemer.webp'),
('Athens', 'The Acropolis of Athens is an ancient citadel built on a rocky hill above the city, serving as a prominent religious and political center in ancient Greece. It''s a collection of ancient temple and building ruins, with the Parthenon being its most famous structure. As a UNESCO World Heritage Site, it remains a symbol of Greece and a testament to its cultural and architectural grandeur, attracting millions of visitors to its surviving structures', 'Acropolis, Athens, Greece', 37.9715, 23.7257, '_images/acropolis_of_athens.webp'),
('Hollywood', 'The Hollywood Sign is a 45-foot-tall, 450-foot-long white landmark on Mount Lee, Los Angeles, spelling out "HOLLYWOOD". Originally a temporary 1923 advertisement for "Hollywoodland" housing, it''s now a global symbol of the film industry and the city itself, recognized by its position overlooking the city and its history of preservation efforts.', 'Hollywood Sign, Los Angeles, CA', 34.1341, -118.3215, '_images/hollywood_sign.webp'),
('Red Square', 'Red Square, located in Moscow, is the city''s central and iconic public space, known for its historical significance, grand architecture, and cultural importance. It is bordered by significant structures like the Kremlin, St. Basil''s Cathedral, and the State Historical Museum. The name "Red Square" comes from an Old Russian word that meant both "red" and "beautiful," referring to the beautiful square its inhabitants saw.', 'Red Square, Moscow, Russia', 55.7558, 37.6176, '_images/red_square.jpg'),
('Berlin', 'The Berlin Wall was a fortified border system, primarily made of concrete, that separated West Berlin from East Germany between 1961 and 1989, designed by the East German government to stop its citizens from escaping to the West. The complex, up to 155 km (96 miles) long, included two walls, guard towers, and a mined "death strip" to prevent crossings. It became a powerful symbol of the Cold War and the division of Europe, a "prison" to the West and a defensive barrier to the Soviets.', 'Berlin Wall, Berlin, Germany', 52.5160, 13.3777, '_images/berlin_wall.jpg'),
('Khalifa', 'The Burj Khalifa is the world''s tallest building, a 162-story, mixed-use skyscraper in Dubai, U.A.E., that houses residential units, commercial spaces, and the Armani Hotel. Completed in 2010, its Y-shaped, spiraling design is inspired by Islamic architecture and desert flora, a structure that minimizes the impact of wind and offers extensive views of the city and the Arabian Gulf. The tower''s engineering marvels include a high-performance concrete structure, energy-efficient glass cladding, and a complex plumbing and air conditioning system.', 'Burj Khalifa, Dubai, UAE', 25.1975, 55.2744, '_images/burj_khalifa.jpg');



INSERT INTO stroll_user (username, password, role) VALUES
('appuser', '$2a$10$GT.htEiAcptcoZowszAoJ.Tg08XZwM1VLnnvNStyvTg9yMGCeIRd.','APP_USER'),
('adminuser', '$2a$10$GT.htEiAcptcoZowszAoJ.Tg08XZwM1VLnnvNStyvTg9yMGCeIRd.','ADMIN_USER');